### ISSUE TITLE
Roadmap 2.X

### ISSUE THREAD

**Issue by maxiejbe** [mpashkovskiy/express-oas-generator#66]
Creating this issue as a roadmap (sorted by priority):

Still in `1.X`:
- OpenApi3: PR almost approved #63 
- Warning for `production` env. #64 
- Ensure OpenApi spec file directory #51 
- Preserve OpenApi spec file ` #52 
- Unhandled requests/responses: #50 + #55

`2.X` major version:
- Deprecating init #65 
- Smaller `README.md`, focused on "`advanced`" (unique) usage.

**Comment by kiprasmel** [comment]
For `2.x`, I'd love to have the examples adjusted to the advanced version aswell. Otherwise looking good!

**Comment by maxiejbe** [comment]
> For `2.x`, I'd love to have the examples adjusted to the advanced version aswell. Otherwise looking good!

Sure, will do! Examples + README.md included.

**Comment by mpashkovskiy** [comment]
looks good to me

**Comment by maxiejbe** [comment]
@mpashkovskiy @kiprasmel Guys, after covering minor #72 the priorities for me would be:

**Improving readme**
- [ ] Removing basic usage
- [ ] Document advanced usage properly (`options` object args table: https://docs.github.com/en/github/writing-on-github/organizing-information-with-tables with columns name, required, type, description, default value)
- [ ] Removing or moving down internal library functionality explanations
- [ ] @mpashkovskiy About npm readme, does it take the same README.md? Or we need to update it manually?

**Refactor**
- [ ] Remove basic usage example
- [ ] Updating tests with advanced usage.
- [ ] Updating `examples/with-jest` with advanced usage
- [ ] Promisify instead of callbacks (Suggest to do that by the way). Use `async/await`.
- [ ] Include prettier 

After all that, we can finally deprecate init and ship `2.x`.

Let me know if you like the plan 😄

**Comment by kiprasmel** [comment]
@maxiejbe looks good to me! Let's remove the basic usage example right before we ship `2.x` but not earlier to avoid confusion. :shipit:

**Comment by shaykesheliID** [comment]
@mpashkovskiy Any plans to support express V5?
